# Generated by Django 6.0.3 on 2026-04-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
