# Generated by Django 6.0.3 on 2026-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prayerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='title',
            field=models.CharField(default='My Testimony', max_length=200),
        ),
    ]
