# Generated by Django 6.0.3 on 2026-04-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Direct link to PDF (e.g., Google Drive share link)', null=True),
        ),
    ]
